# Шаблон для воркеров
x-worker-base: &worker-base
  build:
    context: .
    dockerfile: Dockerfile
  working_dir: /var/www/html
  restart: unless-stopped
  volumes:
    - ./:/var/www/html
  depends_on:
    - rabbitmq
    - mysql
  networks:
    - weather-network
services:
  # PHP-FPM сервис для laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - weather-network
    depends_on:
      - mysql

  # Nginx веб-сервер
  nginx:
    image: nginx:alpine
    container_name: weather-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/conf:/etc/letsencrypt
    networks:
      - weather-network
    depends_on:
      - php
  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/conf:/etc/letsencrypt
  # MySQL база данных
  mysql:
    image: mysql:8.0
    container_name: weather-mysql
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather_bot
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - weather-network

  # Redis
  redis:
    image: redis:alpine
    container_name: weather-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - weather-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: weather-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP порт
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - weather-network

  # Очереди
  queue-handle_telegram_webhook:
    <<: *worker-base
    container_name: weather-queue-handle-telegram-webhook
    command: >
      php artisan queue:work rabbitmq
      --queue=handle_telegram_webhook
      --sleep=3 --tries=3 --timeout=90 --backoff=30 --max-time=3600

  queue-send-telegram:
    <<: *worker-base
    container_name: weather-queue-send-telegram
    command: >
      php artisan queue:work rabbitmq
      --queue=send_telegram_message
      --sleep=3 --tries=5 --timeout=120 --backoff=60 --max-time=3600

  queue-get_city_coordinate:
    <<: *worker-base
    container_name: weather-queue-get_city_coordinate
    command: >
      php artisan queue:work rabbitmq
      --queue=get_city_coordinate
      --sleep=3 --tries=3 --timeout=90 --backoff=30 --max-time=3600

networks:
  weather-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  rabbitmq_data:
    driver: local




